# Site settings
title: Patrick Grady
email: soramirr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://soramirr.github.io" # the base hostname & protocol for your 
github_username:  soramirr

# Build settings
markdown: kramdown
